'use strict';

const files = [
   './node_modules/**/jsdoc.json',
   './node_modules/**/__makefile',
   './node_modules/**/gulpfile.js',
   './node_modules/**/gruntfile.js',
   './node_modules/**/authors',
   './node_modules/**/contributors',
   './node_modules/**/contributing',
   './node_modules/**/changes',
   './node_modules/**/changelog',
   './node_modules/**/readme.md',
   './node_modules/**/changelog.md',
   './node_modules/**/test.html',

   './node_modules/**/.tern-project',
   './node_modules/**/.gitattributes',
   './node_modules/**/.npmignore',
   './node_modules/**/.editorconfig',
   './node_modules/**/.eslintrc',
   './node_modules/**/.jshintrc',
   './node_modules/**/.flowconfig',
   './node_modules/**/.documentup.json',
   './node_modules/**/.yarn-metadata.json',
   './node_modules/**/.travis.yml',
   './node_modules/**/.yarn-integrity',
   './node_modules/**/.nvmrc',
   './node_modules/**/.zuul.yml',
   './node_modules/**/.doclets.yml',
   './node_modules/**/.dockerignore',
   './node_modules/**/.dir-locals.el',
   './node_modules/**/.yarn-integrity',
];

const directories = [
   './node_modules/tinycolor2/demo/',
   './node_modules/@icon/feather/icons/',
   './node_modules/@icon/**/icons/',
   './node_modules/@icon/ionicons/icons/',
   './node_modules/inter-ui/inter??web?',
   './node_modules/google-material-color/node_modules/',

   './node_modules/zxcvbn/src/',
   './node_modules/zxcvbn/dist/',
   './node_modules/windows-10-icons/svg',
   './node_modules/windows-10-icons/svgset',

   './node_modules/**/docs/',
   './node_modules/**/doc/',
   './node_modules/**/tests/',
   './node_modules/**/test/',
   './node_modules/**/powered-test/',
   './node_modules/**/website/',
   './node_modules/**/example/',
   './node_modules/**/examples/',
   './node_modules/**/changelogs/',
   './node_modules/**/coverage/',
   './node_modules/**/demo/',

   './node_modules/notevil/node_modules/esprima/test/',
   './node_modules/deep-diff/examples/',

   './node_modules/@icons/material/**',
   '!./node_modules/@icons/material/**/*UnfoldMoreHorizontalIcon*',
   '!./node_modules/@icons/material/**/*CheckIcon*',
];

const filesFull = [
   './node_modules/roboto-fontface/**/*.woff',
   './node_modules/inter-ui/**/*.woff',

   './node_modules/@mdi/font/fonts/materialdesignicons-webfont.svg',
   './node_modules/@mdi/font/fonts/materialdesignicons-webfont.ttf',
   './node_modules/@mdi/font/fonts/materialdesignicons-webfont.woff',

   './node_modules/@icon/fontawesome-brands/fontawesome-brands.eot',
   './node_modules/@icon/fontawesome-brands/fontawesome-brands.woff',
   './node_modules/@icon/fontawesome-brands/fontawesome-brands.svg',
   './node_modules/@icon/fontawesome-brands/fontawesome-brands.ttf',

   './node_modules/@icon/fontawesome-regular/fontawesome-regular.eot',
   './node_modules/@icon/fontawesome-regular/fontawesome-regular.woff',
   './node_modules/@icon/fontawesome-regular/fontawesome-regular.svg',
   './node_modules/@icon/fontawesome-regular/fontawesome-regular.ttf',

   './node_modules/@icon/fontawesome-solid/fontawesome-solid.eot',
   './node_modules/@icon/fontawesome-solid/fontawesome-solid.woff',
   './node_modules/@icon/fontawesome-solid/fontawesome-solid.svg',
   './node_modules/@icon/fontawesome-solid/fontawesome-solid.ttf',

   './node_modules/windows-10-icons/font/index.html',
   './node_modules/windows-10-icons/font/icons8-win10.svg',
   './node_modules/windows-10-icons/font/icons8-win10.eot',
   './node_modules/windows-10-icons/font/icons8-win10.ttf',
   './node_modules/windows-10-icons/index.html',

   './node_modules/@material-ui/core/umd/material-ui.development.js',

   './node_modules/@fortawesome/free-solid-svg-icons/index.es.js',
   './node_modules/@fortawesome/free-solid-svg-icons/index.js',
   './node_modules/@fortawesome/free-regular-svg-icons/index.es.js',
   './node_modules/@fortawesome/free-regular-svg-icons/index.js',
   './node_modules/@fortawesome/free-brands-svg-icons/index.es.js',
   './node_modules/@fortawesome/free-brands-svg-icons/index.js',

   './node_modules/mdl2-icons/fonts/mdl2.svg',
   './node_modules/mdl2-icons/fonts/mdl2.eot',
   './node_modules/mdl2-icons/fonts/mdl2.ttf',
   './node_modules/mdl2-icons/fonts/mdl2.woff',

   './node_modules/octicons-styl/octicons/octicons.svg',

   './node_modules/uiw-iconfont/fonts/w-icon.svg',
   './node_modules/uiw-iconfont/fonts/w-icon.symbol.svg',
   './node_modules/uiw-iconfont/fonts/w-icon.eot',
   './node_modules/uiw-iconfont/fonts/w-icon.ttf',
   './node_modules/uiw-iconfont/fonts/w-icon.woff',
   './node_modules/uiw-iconfont/icon',

   './node_modules/@icon/feather/feather.svg',
   './node_modules/@icon/ionicons/ionicons.ttf',
   './node_modules/@icon/ionicons/ionicons.woff',
   './node_modules/@icon/ionicons/ionicons.svg',
   './node_modules/electron/dist/LICENSES.chromium.html',
   './node_modules/caniuse-db/fulldata-json/data-2.0.json',
   './node_modules/caniuse-db/data.json',
   './node_modules/caniuse-db/fulldata-json/data-1.0.json',
   './node_modules/@mdi/font/preview.html',
   './node_modules/@mdi/font/scss/_variables.scss',
];

const _ignoreProd = [
   '/_data',
   '/_data_fast',
   '/_data_test',
   '/_data_capture',
   '/_dev',
   '/_choco',
   '/_report',
   '/_test',
   '/_sub_pry',
   '/_sub_der',
   '/_electrons',
   '/_benchmarks',
   '/_node_modules',
   '/_local_node_modules',
   '/_packages',
   '/packages_dev',
   '/__out',
   '/_out',
   '/node_modules_',
   '/package-lock.json',
   '/app/packages_dev',
   '/app/css/.styl',
   /**/
   '/babel.config.js',
   '/node_modules/prettier/',
   '/node_modules/iohook/.vscode',
   '/node_modules/iohook/.vscode/',
   '/.cache/@babel',
   /**/
   '/node_modules/react-test-renderer',
   '/node_modules/JSONStream/test/',
   '/node_modules/iconv/deps/',
   '/node_modules/@fortawesome',

   '/node_modules/ffi-napi/deps/libffi/configure',
   '/node_modules/ffi-napi/deps/',
   '/node_modules/ref/test/',
   /**/
   '/node_modules/react-reconciler/cjs/react-reconciler.development.js',
   '/node_modules/react-dom/umd/react-dom-unstable-fire.development.js',
   /**/
   '\\.bat',
   '\\.cmd',
   '\\.py',
   '\\.zip',
   '\\.rar',
   '\\.gz',
   '\\.tar',
   '\\.sublime-workspace',
   '\\.DS_Store',
   '\\.eslintignore',
   '\\.map',
   '\\.less',
   '\\.styl',
   '\\.lock',
   '\\.log',
   '\\.ts',
   '\\.jst',
   '\\.eot',
   '\\.otf',
   '\\.coffee',
   '\\.flow',
   '\\.tgz',
   '\\.tlog',
   '\\.nyc_output',
   '\\.gitignore',
   '\\.github',
   '\\._compilerc',
   '\\.-lock.json',
   '\\.tlog',
   '\\.ilk',
];

const _ignoreDevExp = [
   './node_modules/**/node_modules/lodash',
   './node_modules/@icon/fontawesome-solid/icons/',
   './node_modules/@icon/fontawesome-brands/icons/',
   './node_modules/@icon/fontawesome-regular/icons/',
   './node_modules/@icon/**/icons/*.svg',
   './node_modules/material-ui/svg-icons/**/*.svg',
];

const _ignoreProdExp = ['/node_modules/uglify-js', '\\.pdb', '\\.Makefile'];

module.exports = {
   dev: [...filesFull, ...directories, ...files, ..._ignoreDevExp],
   prod: [..._ignoreProd, ..._ignoreProdExp],
};
