module.exports = {
  angular: '_iconfont mdi-angular palette-Red-A700 text',
  angularjs: '_iconfont mdi-angularjs palette-Red-A700 text',
  ansible: 'ansible.png',
  apache: 'apache.png',
  apache_pig: 'apache_pig.png',
  backbone: 'backbone.png',
  bootstrap: '_iconfont mdi-bootstrap palette-Deep-Purple-A400 text',
  bower: 'bower.png',
  c: '_iconfont mdi-language-c palette-Blue-A300 text',
  cakephp: 'cakephp.png',
  chai: 'chai.png',
  chef: 'chef.png',
  clojure: 'clojure.png',
  codeigniter: 'codeigniter.png',
  coffeescript: '_iconfont mdi-coffee palette-Orange-A100 text',
  cordova: 'cordova.png',
  cpp: '_iconfont mdi-language-cpp palette-Blue-A300 textg',
  crystal: 'crystal.png',
  css: '_iconfont mdi-language-css3 palette-Blue-A300 text',
  d3: 'd3.png',
  doc: 'doc.png',
  docker: 'docker.png',
  dojo: 'dojo.png',
  dom: 'dom.png',
  dom_events: 'dom_events.png',
  drupal: 'drupal.png',
  elixir: 'elixir.png',
  ember: 'ember.png',
  erlang: 'erlang.png',
  express: 'express.png',
  fish: 'fish.png',
  flow: 'flow.png',
  gcc: 'gcc.png',
  git: '_iconfont mdi-git palette-Red-A200 text',
  gnu_fortran: 'gnu_fortran.png',
  go: 'go.png',
  grunt: 'grunt.png',
  haskell: 'haskell.png',
  haxe: 'haxe.png',
  html: '_iconfont mdi-language-html5 palette-Red-A200 text',
  http: 'http.png',
  icon: 'icon.png',
  influxdata: 'influxdata.png',
  javascript: '_iconfont mdi-language-javascript palette-Amber-A200 text',
  jquery: '_iconfont mdi-currency-usd palette-Blue-A100 text',
  jquerymobile: 'jquerymobile.png',
  jqueryui: 'jqueryui.png',
  knockout: 'knockout.png',
  kotlin: 'kotlin.png',
  laravel: 'laravel.png',
  less: 'less.png',
  lodash: '_iconfont feather-minus palette-Light-Blue-A200 text',
  love: 'love.png',
  lua: 'lua.png',
  marionette: 'marionette.png',
  markdown: '_iconfont mdi-markdown palette-Orange-A200 text',
  maxcdn: 'maxcdn.png',
  meteor: 'meteor.png',
  minitest: 'minitest.png',
  mocha: 'mocha.png',
  modernizr: 'modernizr.png',
  moment: '_iconfont mdi-timer palette-Teal-A700 text',
  mongoose: 'mongoose.png',
  nginx: 'nginx.png',
  nginx_lua_module: 'nginx_lua_module.png',
  node: '_iconfont mdi-nodejs palette-Light-Green-A500 text',
  nokogiri: 'nokogiri.png',
  npm: '_iconfont mdi-npm palette-Red-A700 text',
  padrino: 'padrino.png',
  perl: 'perl.png',
  phalcon: 'phalcon.png',
  phaser: 'phaser.png',
  php: '_iconfont mdi-language-php palette-Indigo-A400 text',
  phpunit: 'phpunit.png',
  plugin: 'plugin.png',
  postgres: 'postgres.png',
  postgresql: 'postgresql.png',
  python: '_iconfont mdi-language-python palette-Amber-A400 text',
  q: 'q.png',
  rails: 'rails.png',
  ramda: 'ramda.png',
  rdoc: 'rdoc.png',
  react: '_iconfont mdi-react palette-Cyan-A400 text',
  react_native: '_iconfont mdi-react palette-Cyan-A400 text',
  redis: 'redis.png',
  redux: 'redux.png',
  rethinkdb: 'rethinkdb.png',
  ruby: '_iconfont mdi-diamond palette-Red-A700 text',
  rust: 'rust.png',
  sass: 'sass.png',
  sinon: 'sinon.png',
  socketio: 'socketio.png',
  sphinx: 'sphinx.png',
  sphinx_simple: 'sphinx_simple.png',
  support_tables: 'support_tables.png',
  svg: 'svg.png',
  symfony: 'symfony.png',
  tcl_tk: 'tcl_tk.png',
  tensorflow: 'tensorflow.png',
  typescript: '_iconfont mdi-language-typescript plette-Blue-A700 text',
  underscore: 'underscore.png',
  vagrant: 'vagrant.png',
  vue: 'vue.png',
  webpack: '_iconfont mdi-webpack palette-Light-Blue-A100 text',
  xslt_xpath: 'xslt_xpath.png',
  yii: 'yii.png'
};
